# Generated by Django 3.1.4 on 2021-03-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headline_content', models.TextField()),
                ('Headline_link', models.CharField(max_length=200)),
                ('Headline_title', models.CharField(max_length=200)),
                ('Polarity', models.FloatField(null=True)),
                ('Comment', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
