# Generated by Django 3.1.4 on 2021-03-17 14:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextInputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_body', ckeditor.fields.RichTextField(default='Enter your text here')),
                ('keyword', models.CharField(max_length=20)),
                ('polarity', models.FloatField(null=True)),
                ('subjectivity', models.FloatField(null=True)),
                ('comment', models.CharField(max_length=20, null=True)),
                ('sub_comment', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
